slot-tick-sound: "BLOCK_NOTE_HARP"  #Sound the plays when the player rolls the slot machine

buy-in: 5.00  #  How much money it costs to play the game for 1 roll

### Messaging ###

not-enough-money: "&c&lSorry! You don't have enough money to play!"  # Message displayed to the player when they have less than the buy-in amount in their account
already-playing: "&c&lYou are already playing Slots!"  # Message displayed to the player when they run command /slots play when they are already playing the game

#################

###  Jackpots - This configuration defines the payout for each jackpot  ###
###  A player wins a jackpot when three of the same image are displayed as the result of rolling the slot machine  ###

jackpots:

  coin-jackpot:    # 1/5 (20%) chance of rolling this jackpot. This is the most common jackpot
    name: "Coin Jackpot"
    payout: 15.00  # How much money the slot machine will pay out when the player wins this jackpot

  ring-jackpot:    # 1/8 (12.5%) chance of rolling this jackpot
    name: "Ring Jackpot"
    payout: 20.00

  star-jackpot:    # 1/12 (8.3%) chance of rolling this jackpot
    name: "Star Jackpot"
    payout: 30.00

  tnt-jackpot:     # 1/20 (5%) chance of rolling this jackpot
    name: "TNT Jackpot"
    payout: 50.00

  trophy-jackpot:  # 1/100 (1%) chance of rolling this jackpot
    name: "Trophy Jackpot"
    payout: 250.00