name: Slots
main: com.antarescraft.kloudy.slots.Slots
version: 1.0
author: Kloudy
website: www.antarescraft.com

depend: [HoloGUIApi, Vault]

commands:
  slots:
    description: used to define commands for the Slots plugin

permissions:

  slots.play:
    description: Allows a player to play Slots
    default: true